CREATE TABLE ORDERITEMS(
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL ,
  product_id INT NOT NULL ,
  quantity INTEGER NOT NULL,
  amount FLOAT NOT NULL ,
  FOREIGN KEY (order_id) REFERENCES ORDERS(id),
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);